config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#oauth'

  resources :categories
  resources :questions do
    resources :answers, only: %i[new create index]
  end
  resources :answers, only: %i[index destroy edit update]
  resources :users, except: [:new]
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 6, maximum: 1000 }
  validates :content, presence: true, length: { minimum: 20, maximum: 3500 }

  scope :answered, -> { where(answered: true) }
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    @answers = @question.answers.last(3)
  end

  # Move the logic to the models
  def index
    @questions = if params[:sort] == 'answered'
                   Question.answered.paginate(page: params[:page], per_page: 5)
                 elsif params[:sort]
                   Question.where('category_id = ?', params[:sort]).paginate(page: params[:page], per_page: 5)
                 elsif params[:search]
                   Question.where('content or title LIKE ?', "%#{params[:search]}%").paginate(page: params[:page],
                                                                                              per_page: 5)
                 else
                   Question.order('created_at DESC').paginate(page: params[:page], per_page: 5)
                 end
  end

  def new
    @question = Question.new
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def create
    @question = current_user.questions.build(question_params)
    # @question.user = current_user
    if @question.save
      flash[:success] = 'Save succesful!'
      redirect_to @question
    else
      render 'new'
    end
  end

  def destroy
    @question.delete
    redirect_to questions_path
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :content, :category_id)
  end

  def require_same_user
    if current_user != @question.user && !current_user.admin
      flash[:danger] = 'You can only edit or delete your own questions'
      redirect_to @question
    end
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @question %>
      <%= form_with(model: @question, class: "shadow p-3 mb-5 bg-secondary rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Please add a descriptive title..." %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :content, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.text_area :content, rows: 10, class: "form-control shadow rounded", placeholder: "Include as many details as you can so other users can offer help..." %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-white" %>
          <div class="col-10">
            <%= f.select :category_id, Category.all.collect {|x| [x.name.titleize, x.id]}, {}, class: "multiple form-control" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light"%>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to question list ]', questions_path, class: "text-secondary" %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1 class="text-center mt-4"> Edit Question </h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<h1 class="text-center mt-4">Index of Questions</h1>
<div class="container text-center">
  <small>
    <%= @questions.answered.count %> of <%= @questions.count %> Questions have been 
    <%= link_to "answered", questions_path(:sort => "answered"), title: "Show only questions that have been answered" %>
  </small>
</div>
<div class="flickr_pagination">
  <%= will_paginate @questions, :container => false %>
</div>
<%= render 'users/questions' %>
<div class="flickr_pagination">
  <%= will_paginate @questions, :container => false %>
</div>

app/views/questions/new.html.erb
<h1 class="text-center mt-4"> Create New Question </h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<h2 class="text-center mt-4"> <%= @question.title %> </h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Asked by: <%= @question.user.username.titleize %>
          <small><%= time_ago_in_words(@question.created_at) %> ago</small>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@question.content) %></div>
          <% if logged_in? %>
            <%= link_to 'Give an Answer', new_question_answer_path(@question), class: "btn btn-outline-dark" %>
          <% end %>
          <% if logged_in? && (@question.user == current_user || current_user.admin?) %>
            <%= link_to 'Edit', edit_question_path(@question), class: "btn btn-outline-dark" %>
            <%= link_to 'Delete', question_path(@question), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger"  %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>
            <small class="text-left">Category:  <%= @question.category.name.capitalize %></small>
          </small>
        </div>
      </div>
      <hr/>
      <h4 class="text-center my-4">Latest Answers:</h4>
      <% @answers.each do |a| %>
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            Answered by: <%= a.user.username.titleize %>
            <small><%= time_ago_in_words(a.created_at) %> ago</small>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(a.content) %></div>
            <% if logged_in? && (a.user == current_user || current_user.admin?) %>
              <%= link_to 'Edit', edit_answer_path(a), class: "btn btn-outline-dark" %>
              <%= link_to 'Delete', answer_path(a), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger"  %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="container">
        <div class="row justify-content-md-center">
          <%= link_to 'See all answers for this question', question_answers_path(@question), class: "btn btn-outline-dark" %>
        </div>
      </div>
    </div>
  </div>
</div>