config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#oauth'

  resources :categories
  resources :questions do
    resources :answers, only: %i[new create index]
  end
  resources :answers, only: %i[index destroy edit update]
  resources :users, except: [:new]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 mt-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; <a id="sticky-link"href="https://github.com/mavrik83/aeroflow" target=”_blank”>mavrik83</a></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |key, msg| %>
    <div class="alert alert-<%=key%> alert-dismissible fade show" role="alert">
      <h6><strong><%= msg %></strong></h6>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to "AeroFlow", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if logged_in? && current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Members", users_path, class: "nav-link", id: "member-link" %>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Questions
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Ask a Question", new_question_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View All Questions", questions_path, class: "dropdown-item" %>
          <% if logged_in? && current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to "View All Answers", answers_path, class: "dropdown-item text-info" %>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.username.titleize %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <% if logged_in? && current_user.admin? %>
      <div class="text-info">
        ADMIN
      </div>
    <% end %>
      <%= form_with(url: "/questions", method: "get", class: "form-inline my-2 my-lg-0", local: true) do %>
        <%= text_field_tag(:search, "", class: "form-control mr-sm-2") %>
        <%= submit_tag("Search", class: "btn btn-outline-light my-2 my-sm-0") %>
      <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aeroflow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>